name = "your-ai-chatbot"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[ai.models]]
binding = "llama"
model = "@cf/meta/llama-3.1-8b-instruct"

# D1 Database for conversations, teams, appointments
[[d1_databases]]
binding = "DB"
database_name = "your-ai-chatbot"
database_id = "your-d1-database-id"

# KV Namespace for chat sessions
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-namespace-id"

# Optional: R2 bucket for file storage
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "your-ai-files"

# For local development with remote bindings
[env.local]
name = "your-ai-chatbot"
[[env.local.d1_databases]]
binding = "DB"
database_name = "your-ai-chatbot"
database_id = "your-d1-database-id"
experimental_remote = true

[[env.local.kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-kv-preview-namespace-id"
experimental_remote = true 