name: Setup Node, Install, Build, (Optional) Wrangler
description: Common setup steps for CI jobs
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20'
  run-build:
    description: Run npm run build
    required: false
    default: 'true'
  install-wrangler:
    description: Install Wrangler globally
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build frontend
      if: ${{ inputs.run-build == 'true' }}
      shell: bash
      run: npm run build

    - name: Install Wrangler
      if: ${{ inputs.install-wrangler == 'true' }}
      shell: bash
      run: npm install -g wrangler
