/**
 * Shared intake template constants.
 *
 * This file is the single source of truth for the default template field list
 * and the set of keys that map directly to IntakeConversationState (standard fields).
 * Both the worker (aiChatIntake.ts, widget.ts) and the frontend (useIntakeFlow,
 * IntakeDetailPage) import from here — nothing else should re-define these.
 */

import type { IntakeFieldDefinition } from '../types/intake';

/** All field definitions that map onto existing IntakeConversationState keys. */
export const STANDARD_FIELD_DEFINITIONS: IntakeFieldDefinition[] = [
  {
    key: 'description',
    label: 'Case description',
    type: 'text',
    required: true,
    phase: 'required',
    isStandard: true,
    mapsTo: 'description',
    completenessWeight: 25,
    description: 'A short summary of what happened.',
    validationHint: 'A concise plain-language summary of the legal issue in the client’s own words.',
    previewQuestion: 'Can you tell me what happened in your own words?',
    promptHint: 'Ask them to describe their situation in their own words. Keep it open-ended and warm — you want the full story, not a one-liner. If they give you a lot of detail, extract city/state/opposing party from their answer before asking separately.',
  },
  {
    key: 'city',
    label: 'City',
    type: 'text',
    required: true,
    phase: 'required',
    isStandard: true,
    mapsTo: 'address.city',
    completenessWeight: 8,
    description: 'The city where the legal issue happened.',
    validationHint: 'A city name only, without a street address.',
    previewQuestion: 'What city did this happen in?',
    promptHint: 'Ask for the city where the incident or matter occurred — the venue, not their home address. Keep it brief. If they already mentioned a city in their description, extract it instead of asking.',
  },
  {
    key: 'state',
    label: 'State',
    type: 'text',
    required: true,
    phase: 'required',
    isStandard: true,
    mapsTo: 'address.state',
    completenessWeight: 7,
    description: 'The state or jurisdiction for the issue.',
    validationHint: 'A US state name or 2-letter abbreviation.',
    previewQuestion: 'What state did this happen in?',
    promptHint: 'Ask for the state or jurisdiction. Accept full state names or abbreviations. If city and state were given together, extract both at once. If they already mentioned a state, do not ask again.',
  },
  {
    key: 'urgency',
    label: 'Urgency',
    type: 'select',
    required: false,
    phase: 'enrichment',
    options: ['routine', 'time_sensitive', 'emergency'],
    isStandard: true,
    mapsTo: 'urgency',
    completenessWeight: 12,
    description: 'Routine, time-sensitive, or emergency.',
    validationHint: 'One of: routine, time_sensitive, emergency.',
    previewQuestion: 'How urgent does this feel: routine, time-sensitive, or emergency?',
    promptHint: 'Ask how time-sensitive this matter is. Frame it in plain language — not the option labels. For example: "Is this something that needs immediate attention, or is it more of a longer-term concern?" Accept any phrasing and map to the closest option. If they mentioned a court date or deadline earlier, you likely already know the answer.',
  },
  {
    key: 'practiceServiceUuid',
    label: 'Practice area',
    type: 'select',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'practice_service_uuid',
    completenessWeight: 8,
    description: 'The practice service or matter type.',
    validationHint: 'Exactly one service from the firm service list.',
    previewQuestion: 'Which type of legal help are you looking for?',
    promptHint: 'Only ask this if the practice offers multiple services AND the case type is genuinely ambiguous from the conversation. Reference the services list by name. If the situation clearly maps to one service, save it without asking.',
  },
  {
    key: 'opposingParty',
    label: 'Opposing party',
    type: 'text',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'opposing_party',
    completenessWeight: 12,
    description: 'The person, company, or organization on the other side.',
    validationHint: 'The name or description of the other person, company, or organization involved.',
    previewQuestion: 'Who is on the other side of this issue?',
    promptHint: 'Ask who is on the other side of the matter — a person, company, landlord, employer, etc. If they already named the opposing party in their description (e.g. "my landlord Johnson Properties"), extract it without asking. Use their own framing: "the other party", "your landlord", "the employer" — not "opposing party".',
  },
  {
    key: 'desiredOutcome',
    label: 'Desired outcome',
    type: 'text',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'desired_outcome',
    completenessWeight: 12,
    description: 'What the client hopes the practice can help achieve.',
    validationHint: 'A short plain-language statement of the outcome the client wants.',
    previewQuestion: 'What outcome are you hoping for?',
    promptHint: 'Ask what they are hoping to achieve. Keep it conversational: "What would a good outcome look like for you?" or "What are you hoping the attorney can help you get?" Avoid legal jargon. If they already stated a goal (e.g. "I want my deposit back"), extract it.',
  },
  {
    key: 'courtDate',
    label: 'Court date',
    type: 'date',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'court_date',
    completenessWeight: 10,
    description: 'Any court date, hearing, or deadline.',
    validationHint: 'YYYY-MM-DD, or leave empty if there is no date yet.',
    previewQuestion: 'Is there a court date, hearing, or deadline coming up?',
    promptHint: 'Ask if there is an upcoming court date, hearing, or hard deadline. Accept any date format and convert to ISO. If they already mentioned a date or deadline in the conversation, extract it. If they say "no" or "not yet", record null.',
  },
  {
    key: 'hasDocuments',
    label: 'Has documents',
    type: 'boolean',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'has_documents',
    completenessWeight: 6,
    description: 'Whether the client has documents to share.',
    validationHint: 'true or false.',
    previewQuestion: 'Do you have any documents related to this?',
    promptHint: 'Ask whether they have any relevant documents — contracts, leases, emails, photos, police reports, etc. Keep it simple: "Do you have any paperwork or records related to this?" A yes/no answer is all you need.',
  },
  {
    key: 'householdSize',
    label: 'Household size',
    type: 'number',
    required: false,
    phase: 'enrichment',
    isStandard: true,
    mapsTo: 'household_size',
    completenessWeight: 0,
    description: 'Household size for eligibility review.',
    validationHint: 'A whole number greater than or equal to 1.',
    previewQuestion: 'How many people are in your household?',
    promptHint: 'Only ask this when it is clearly relevant — for example, family law matters, housing cases, or when the practice has indicated it is needed for fee eligibility. Explain briefly why: "This helps the attorney understand your household situation." Skip this field entirely for business disputes, criminal matters, or other case types where it does not apply.',
  },
];

/**
 * The set of keys that belong to IntakeConversationState directly.
 * Used by aiChatIntake.ts to route tool-call values to the right bucket.
 */
export const STANDARD_FIELD_KEYS: ReadonlySet<string> = new Set(
  STANDARD_FIELD_DEFINITIONS.map((f) => f.key),
);
