export { handleHealth } from './health';
export { handleRoot } from './root';
export { handleAuthProxy, handleBackendProxy } from './authProxy';
export { handlePractices } from './practices';
export { handleActivity } from './activity';
export { handleConfig } from './config';
export { handlePracticeDetails } from './practiceDetails';
export { handleAiChat } from './aiChat';
export { handleAiIntent } from './aiIntent';
export { handleParalegal } from './paralegal';
export { handleFiles } from './files';
export { handleAnalyze } from './analyze';
export { handleNotifications } from './notifications';
export { handlePDF } from './pdf';
export { handleDebug } from './debug';
export { handlePracticeIntakeCreate } from './intakes';