-- Migration removed: Enhanced pii_access_audit table is now in schema.sql
-- This migration was redundant since schema.sql already includes:
--   - All encrypted PII fields (ip_address_encrypted, user_agent_encrypted, etc.)
--   - Retention metadata (retention_expires_at, deleted_at, retention_policy_id)
--   - Consent tracking (consent_id, legal_basis, consent_version)
--   - All indexes
-- Date removed: 2025-01-08
-- 
-- If you have an existing database that needs these, they should already exist
-- from when this migration was first run. Fresh databases get everything from schema.sql.
