-- Migration temporarily disabled: D1 migration system has issues with multiple CREATE INDEX statements
-- These indexes can be created manually if needed:
--   CREATE INDEX IF NOT EXISTS idx_matters_org_status_created_at ON matters(organization_id, status, created_at DESC);
--   CREATE INDEX IF NOT EXISTS idx_matter_events_matter_type_date ON matter_events(matter_id, event_type, event_date DESC);
-- 
-- Note: These indexes are for performance optimization and are not required for the database to function
-- Date disabled: 2025-01-08
