-- Migration removed: All columns are now in schema.sql
-- This migration was redundant since schema.sql already includes all user preference columns
-- Date removed: 2025-01-18
-- 
-- If you have an existing database that needs these columns, they should already exist
-- from when this migration was first run. Fresh databases get everything from schema.sql.
