import { FunctionalComponent } from 'preact';
import { ExclamationTriangleIcon } from "@heroicons/react/24/outline";
import { analyzeMissingInfo } from '../utils/matterAnalysis';
import { MatterStatusBadge } from './matters/StatusBadge';
import { MatterWorkflowStatus } from '../hooks/useOrganizationManagement';

interface MatterCanvasProps {
  matterId?: string;
  matterNumber?: string;
  service: string;
  matterSummary: string;
  status?: MatterWorkflowStatus;
  
  answers: Record<string, string | { question: string; answer: string }>;
}

/**
 * Case Summary component - displays matter details with missing information analysis
 * Shows markdown content with professional matter tracking
 */
const MatterCanvas: FunctionalComponent<MatterCanvasProps> = ({
  matterId: _matterId,
  matterNumber: _matterNumber,
  service,
  matterSummary,
  status,
  answers: _answers
}) => {

  const effectiveStatus: MatterWorkflowStatus = status ?? 'lead';

  // Generate markdown content for the matter - CLIENT-FACING ONLY
  const generateMarkdown = () => {
    // Only show the matter summary that was generated by AI for the client
    // No internal metrics, scores, or assessments
    return matterSummary;
  };

  const markdownContent = generateMarkdown();
  const missingInfo = analyzeMissingInfo({
    service,
    matterSummary,
    status: 'ready' as const
  });

  return (
    <div className="matter-canvas">
      <div className="flex items-center justify-between mb-4">
        <MatterStatusBadge status={effectiveStatus} />
        <span className="text-sm text-gray-600 dark:text-gray-300">
          {effectiveStatus === 'lead' ? 'Waiting for review' : effectiveStatus.replace('_', ' ')}
        </span>
      </div>
      <div className="matter-canvas-content">
        <pre className="matter-canvas-markdown">
          {markdownContent}
        </pre>
        
        {/* Show missing information */}
        {missingInfo.length > 0 && (
          <div className="missing-info-section">
            <div className="missing-info-header">
              <ExclamationTriangleIcon className="w-4 h-4" />
              <span>Missing Information</span>
            </div>
            <div className="missing-info-list">
              <p>To strengthen your matter, consider providing:</p>
              <ul>
                {missingInfo.map((info, index) => (
                  <li key={index}>{info}</li>
                ))}
              </ul>
              <p className="missing-info-note">
                You can provide this information by continuing our conversation. 
                The more details you share, the better we can assist you.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default MatterCanvas; 
